apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/serkan4545/bootstrap.git
    targetRevision: HEAD
    path: apps/gitea
    helm:
      valueFiles:
        - apps/gitea/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true