apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/serkan4545/bootstrap.git  # Dein Repo
    path: apps
    targetRevision: HEAD  # Immer die neueste Version des Repos verwenden
    helm:
      valueFiles:
        - apps/gitea/chart/gitea/values.yaml  # Deine benutzerdefinierte Werte-Datei
  destination:
    server: https://kubernetes.default.svc  # Ziel Kubernetes-Cluster
    namespace: argocd  # Namespace für die ArgoCD-Anwendung
  syncPolicy:
    automated:
      prune: true
      selfHeal: true