service:
  http:
    type: NodePort
    port: 3000

ingress:
  enabled: false

persistence:
  enabled: true
  size: 10Gi
  storageClass: standard

postgresql:
  enabled: true
  auth:
    postgresPassword: gitea
    username: gitea
    password: gitea
    database: gitea