ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: gitea.local
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  size: 10Gi
  storageClass: standard

postgresql:
  enabled: true
  auth:
    postgresPassword: gitea
    username: gitea
    password: gitea
    database: gitea